### ISSUE TITLE
Unused context menu entries "Create New View for Output" / "New Console for Notebook"

### ISSUE THREAD

**Issue by chmp** [jupyterlab/retrolab#104]
When I right-click inside a cell, I get two entries in the context menu, that don't perform any function as far as I can tell:

- Create New View for Output
- New Console for Notebook

No real issue, but I guess it could be confusing to new users.

**Comment by jtpio** [comment]
Thanks @chmp.

> - Create New View for Output

Maybe this upstream JupyterLab functionality could be moved into its own plugin. Then JupyterLab Classic would not include the plugin in the build.

> - New Console for Notebook

Similarly this could also be a separate plugin in JupyterLab.

Or be implemented in JupyterLab Classic to also support code consoles: https://github.com/jtpio/jupyterlab-classic/issues/49

**Comment by jtpio** [comment]
@chmp there is now a [`0.3.0a0`](https://github.com/jtpio/retrolab/releases/tag/0.3.0a0) release of `retrolab` (following up the [rename](#118)), which grabs some upstream improvements.

The "Create New View for Output" should now be gone.

The "New Console for Notebook" is still visible:

![image](https://user-images.githubusercontent.com/591645/119093828-80518000-ba10-11eb-99fc-da2590cba37f.png)

As well as the "Create Console for Editor" when opening a new file:

![image](https://user-images.githubusercontent.com/591645/119093804-7465be00-ba10-11eb-8c97-e4225e7d184c.png)

**Comment by chmp** [comment]
Thanks for the heads up (also of the rename). Happy to give it a try. 

Btw. I have been using retrolab as my excluive jupyter interface for some while now and am extremely happy with it.

**Comment by krassowski** [comment]
Would this work: https://github.com/jupyterlab/jupyterlab/pull/10254 on making menus configurable make it easier for you here @jtpio ? Thinking that such an approach could allow for flexibility while avoiding further proliferation of very small packages.

**Comment by jtpio** [comment]
Thanks @krassowski :+1: 

> Thinking that such an approach could allow for flexibility while avoiding further proliferation of very small packages.

I think so yes. Otherwise it would have meant moving the command to a separate plugin:

https://github.com/jupyterlab/jupyterlab/blob/abcb9242af1a97fa9e897d34f0556e07bb913fa3/packages/mainmenu-extension/src/index.ts#L364-L382

But could feel a bit off if only the `createConsole` command is moved to a separate plugin while all the others are added by the same plugin.

**Comment by jtpio** [comment]
The "New Console for Notebook` could actually be kept if we end up implementing #49
