### ISSUE TITLE
Make it easier to find the Retro tree

### ISSUE THREAD

**Issue by danlester** [jupyterlab/retrolab#134]
Thank you very much for this repo!

Actually, I am looking into using Retro because I want to write automated Javascript tests for our QHub JupyterHub environment, and it is difficult to locate specific UI elements in a predictable manner in regular JupyterLab. Maybe Retro will make that easier...

Anyway, when I first installed it I struggled to actually understand how to access it from JupyterLab. I don't think there is documentation that says exactly what you need to do.

I'd seen your screenshots that were at the /retro/... path so I went to /retro and got 404... It was only by trying /retro/tree exactly that I realised things were working after all, I just needed to be specific on the URL.

So it would be great if at least /retro and /retro/ can redirect to /retro/tree, assuming URLs are the recommended route to access Retro. And either way, just to mention what to do in the docs would be really helpful.

Thanks again.

**Comment by jtpio** [comment]
Thanks @danlester.

For now the integration lab -> retro is this icon in the notebook toolbar:

![image](https://user-images.githubusercontent.com/591645/119686715-e726cd00-be46-11eb-8cb4-c2aa0bdf1cfa.png)

Maybe there should be something similar to the "Launch Classic Notebook", but for Retro?

![image](https://user-images.githubusercontent.com/591645/119686814-fefe5100-be46-11eb-91c2-fe21bef15831.png)

**Comment by jtpio** [comment]
> So it would be great if at least /retro and /retro/ can redirect to /retro/tree

Agree it would be great to have :+1:

**Comment by jtpio** [comment]
It would probably require having a similar plugin as the one in JupyterLab:

https://github.com/jupyterlab/jupyterlab/blob/b8725f0ed99b199c535caba6898f5771832e9da9/packages/help-extension/src/index.tsx#L166-L200

That would live in https://github.com/jtpio/retrolab/blob/main/packages/lab-extension/src/index.ts

In case you would like to give it a shot and open a PR :)
