### ISSUE TITLE
Redirect from /retro missing?

### ISSUE THREAD

**Issue by jabbera** [jupyterlab/retrolab#146]
Hi,

I'm unsure if this is a retrolab issue or not. Feel free to close if I'm crazy. Using jupyterlab via jupyterhub I can access jupyter lab via the following url:

https://blah/user/blah/lab

when using retro lab I get a 404 with:

https://blah/user/blah/retro

however adding /tree to the end yields the file browser:

https://blah/user/blah/retro/tree

If this is supposed to be a drop in replacement there should be a transparent redirect here.

**Comment by jtpio** [comment]
@jabbera this was added in https://github.com/jupyterlab/retrolab/pull/138 and should be available in `0.3.0a2`: https://pypi.org/project/retrolab/0.3.0a2/

**Comment by jabbera** [comment]
Thanks! I searched issues but not PRs.
