### ISSUE TITLE
hub-extension from JupyterLab

### ISSUE THREAD

**Issue by jabbera** [jupyterlab/retrolab#147]
I'd love to have the [hub-extension](https://github.com/jupyterlab/jupyterlab/tree/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/hub-extension) brought over from JupyterLab. I don't have the File->Hub Control Panel in Retro Lab when running in JupyterHub.

Cheers,
Mike

**Comment by jtpio** [comment]
Thanks @jabbera, sounds good.

`@jupyterlab/hub-extension` could indeed be added to the `package.json` file here: https://github.com/jupyterlab/retrolab/blob/main/app/package.json and to the list of plugins here:

https://github.com/jupyterlab/retrolab/blob/b28c91c9adde90f429c5fca6b9d49b225fad0f92/app/index.js#L84

Would you like to give it a try in a PR?

**Comment by jabbera** [comment]
Will do. Doesn't work on binder though. I'll see if I can test it internally. Glad you commented I was going to copy it into the packages folder:-)

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/retrolab/pull/148, thanks!
