### ISSUE TITLE
/tree/<path> should redirect to /notebooks/<path> if <path> is a notebook file

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#153]
### Problem

When redirecting users to a particular file (from [nbgitpuller](http://nbgitpuller.link)), it is important to not need prior knowledge on wether the target is a file or a directory. In lab and classic notebook, we can send people to `/tree/<path>`, it redirects to `/notebooks/<path>` if it's a notebook or `/tree/<path>` if it's just a directory, based on what ContentsManager says. 

retrolab doesn't do that - if you go to `/tree/<path>` but `<path>` is a notebook you get an error.

### Proposed Solution

https://github.com/jupyterlab/retrolab/blob/0f7c026472e64b9f9073cce47a00c072d6a84af5/retrolab/app.py#L99 currently handles redirects. We could either figure out a contentsmanager check here, or do that on the client side

**Comment by jtpio** [comment]
Thanks @yuvipanda.

Probably doing the redirect in that handle will be enough. RetroLab should then be able to handle URLs that look like `/retro/notebooks/example.ipynb`
