### ISSUE TITLE
Simple button to switch back to classic notebook

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#157]
### Problem

Retrolab is a great alternative to classic notebook, but bugs will still be found. To ease worries about exposing students to these bugs, having a simple way to switch to classic notebook (without having to fiddle with the URL) would be great.

### Proposed Solution

A built in toolbar button that lets you switch to classic. This could also switch to lab if needed.

**Comment by jtpio** [comment]
Thanks @yuvipanda.

Would having the same "Launch Classic Notebook" menu entry as in JupyterLab work?

![image](https://user-images.githubusercontent.com/591645/121139043-9cd72000-c838-11eb-95cc-284d7f19851c.png)

**Comment by yuvipanda** [comment]
@jtpio yes! Just on the menubar?

**Comment by yuvipanda** [comment]
@jtpio hmm, so it doesn't seem to open to the *currently open notebook* - just generically opens classic notebook. Since we have current context, I think we can do better.

**Comment by jtpio** [comment]
So we can probably add a new plugin to RetroLab for this then.

There is already a plugin to do something similar (installed as a lab extension), but to go from JupyterLab to RetroLab:

![image](https://user-images.githubusercontent.com/591645/121209820-771f3a80-c87b-11eb-8223-a7a4c3d2cb30.png)

https://github.com/jupyterlab/retrolab/blob/0f7c026472e64b9f9073cce47a00c072d6a84af5/packages/lab-extension/src/index.ts#L104-L115
