### ISSUE TITLE
Don't display .ipynb in notebook title

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#160]
### Problem

Notebook files always have the .ipynb extension, so we should not display them. Classic notebook does not.

Classic Notebook:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/30430/121272369-69050480-c8e3-11eb-90d6-1da190547b11.png">

Retrolab:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/30430/121272385-76ba8a00-c8e3-11eb-9987-afec4569e44c.png">

### Proposed Solution

Trip `.ipynb` when displaying name of notebook

**Comment by jtpio** [comment]
Thanks @yuvipanda for the suggestion.

> Notebook files always have the .ipynb extension, so we should not display them. Classic notebook does not.

I think it would be fine to indeed not display the extension. And it saves some space in the top area.

One thing to keep in mind too is that RetroLab doesn't need or claim to be a strict copy of the classic notebook UI, so some differences such as this one would be fine.

**Comment by yuvipanda** [comment]
> One thing to keep in mind too is that RetroLab doesn't need or claim to be a strict copy of the classic notebook UI, so some differences such as this one would be fine.

oh yeah, absolutely. Just looking for inspiration :)

**Comment by jtpio** [comment]
Based on the discussion from other issues (for example https://github.com/jupyterlab/retrolab/issues/259) and the notebook discussion, maybe we'll want to do this to match the classic UI.

The plugin handling the title is defined here:

https://github.com/jupyterlab/retrolab/blob/45f879dc7fbedfda2ee640afe690965bdb14a5eb/packages/application-extension/src/index.ts#L381-L447

It is also activated and used for text files. Classic shows the extension for other files than notebooks:

![image](https://user-images.githubusercontent.com/591645/139862471-25eca29f-40ef-42bc-a1a0-4ee40c28c6d8.png)

So we probably need to special case `.ipynb` in the plugin, and also make sure renaming is still supported.

Marking as good first issue if someone would like to take a look, thanks!
