### ISSUE TITLE
I was expecting /retro/tree/path/foo.ipynb to open the notebook directly

### ISSUE THREAD

**Issue by parmentelat** [jupyterlab/retrolab#162]
### Problem

I'm considering to use retrolab as a replacement to classic/ in an education-oriented tool, where the capability to open one specific notebook from the outside is paramount

pointing my browser at a URL starting with `retro/` I was expecting to be able to open a specific notebook directly 
- like  e.g. `lab/tree/path/foo.ipynb` does

what I observe is the part after `tree/` being ignored, i.e. `retro/tree/path/foo.ipyn` behaves exactly like `retro/`

is this a bug or by design ?

### Proposed Solution

provide the same direct-access capability as vanilla jlab

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

see vanilla jlab

**Comment by jtpio** [comment]
Thanks @parmentelat.

This should now have been fixed by https://github.com/jupyterlab/retrolab/pull/159.

It hasn't been released yet, but you could use this Binder link to try the latest `main` branch on Binder: https://mybinder.org/v2/gh/jupyterlab/retrolab/main?urlpath=retro/tree

**Comment by parmentelat** [comment]
thank you @jtpio this is great ! :) 
when do you expect this to make it to pypi ?

may I push one step further and ask you about the ability to apply the same trick on jupytext notebooks ?

this is an issue that I also experience with plain jupyterlab, as I just described in here
https://discourse.jupyter.org/t/opening-a-jupytext-powered-notebook-under-jlab/9545

I expect this to be less straightforward of an answer, let me know if you'd rather I open a new issue about that

**Comment by jtpio** [comment]
>  when do you expect this to make it to pypi ?

Soon for the `0.3.0` alpha series, waiting for other fixes for `0.2.x`.

> may I push one step further and ask you about the ability to apply the same trick on jupytext notebooks ?

I think jupytext is out of scope for the retrolab project. It would be better to open a new issue on the jupytext repo directly: https://github.com/mwouts/jupytext

Probably this could be implemented as a server extension.

**Comment by jtpio** [comment]
Closing as answered and fixed, thanks!

**Comment by parmentelat** [comment]
thanks!
for the record I'm trying to follow up on this in https://github.com/mwouts/jupytext/issues/803
