### ISSUE TITLE
Publish a new release of jupyterlab-classic to inform about rename

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/retrolab#163]
To make users who earlier installed jupyterlab-classic aware of the rename it might be a good idea to publish a new release of jupyterlab-classic to PyPI/npm/both which would add a note about the rename in the README and maybe a console.log/logging.warn message to inform existing users about the need to update their environment/requirements files.

I think that NPM allows for installation-time logs about this but it might not be visible when installing from extension manager (which one should not do probably for this extension which requires a backend component).

Possibly a good place to put a notice would be the description field as it shows up in the Extension Manager GUI.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/focus-mode-intern-project/1552/24

**Comment by jtpio** [comment]
Thanks @krassowski for the suggestion :+1: 

There is now a `0.1.x` branch that points to the commit before the rename to RetroLab: https://github.com/jupyterlab/retrolab/tree/0.1.x

We could do the change in that branch and then publish the packages.

Would you like to open a PR? Thanks!

**Comment by jtpio** [comment]
Just published a `0.1.11` version to PyPI: https://pypi.org/project/jupyterlab-classic/0.1.11/

![image](https://user-images.githubusercontent.com/591645/165567779-a9eb787c-e290-4e9d-8037-61ee99d659de.png)

Probably this is enough for `jupyterlab-classic`. We'll likely do something similar for RetroLab later: https://github.com/jupyterlab/retrolab/issues/356
