### ISSUE TITLE
Retrolab doesn't warn user if they try to quit without saving

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#165]
## Description

If the current notebook has not been saved while the user tries to leave the page, Retrolab should complain! This makes sure users don't accidentally lose work.

## Reproduce

1. Create a new notebook
2. Type random things into cells
3. Close the browser tab
4. Tab just closes!

## Expected behavior

A warning from the browser, asking if we are sure we want to navigate away from the page.

**Comment by jtpio** [comment]
Thanks Yuvi for opening this.

Probably we need to add the check for `app.status.isDirty` and listen to the `beforeunload` event, like in JupyterLab:

https://github.com/jupyterlab/jupyterlab/blob/96b6ca109fb194d1f011a2f6fe1f4c673d88e6ea/packages/application-extension/src/index.tsx#L552-L565

**Comment by jtpio** [comment]
> Probably we need to add the check for `app.status.isDirty` and listen to the `beforeunload` event, like in JupyterLab:

Or better, we could move this logic to a new `checkDirty` plugin in upstream JupyterLab, and reuse it as-is in RetroLab.

**Comment by jtpio** [comment]
> Or better, we could move this logic to a new `checkDirty` plugin in upstream JupyterLab, and reuse it as-is in RetroLab.

Actually this might not be enough, since `status` seems to be for `JupyterLab` applications only.

So we probably have to add the `status` to RetroLab too, and provide the `ILabStatus` token.

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/retrolab/pull/166
