### ISSUE TITLE
Persist Show Header

### ISSUE THREAD

**Issue by bdch1234** [jupyterlab/retrolab#172]
Would it be possible to have the setting for "Show Header" persist between sessions?

![image](https://user-images.githubusercontent.com/46796385/123950625-2d220400-d9a4-11eb-96eb-a93c1b75a995.png)

**Comment by jtpio** [comment]
Thanks @bdch1234.

Yes it would be better if this could persist. For that we will probably need support for persisting settings for `@retrolab` plugins, which is tracked in https://github.com/jupyterlab/retrolab/issues/4.

**Comment by jtpio** [comment]
Closing as fixed by #265.

This will be released soon, but can be tested on Binder for now: https://mybinder.org/v2/gh/jupyterlab/retrolab/main?urlpath=retro/tree
