### ISSUE TITLE
Find and Replace

### ISSUE THREAD

**Issue by ajye92** [jupyterlab/retrolab#181]
How to find and replace texts globally? I can only do within-cell search by press "cmd + F".

**Comment by jtpio** [comment]
Thanks @ajye92.

It could be because the `@jupyterlab/documentsearch-extension` extension is missing from this list:

https://github.com/jupyterlab/retrolab/blob/7ec1019882df37b920f10e0f03cc5418597c3cd7/app/package.json#L146-L171

**Comment by ajye92** [comment]
Thanks @jtpio. Can you add this extension to 0.3.0rc2 build?

**Comment by jtpio** [comment]
OK, no problem and thanks again for the suggestion!

Tagging as a good first issue in case someone would like to give it a try.
