### ISSUE TITLE
Remove "New console for notebook" menu

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/retrolab#235]
We should probably remove the "New Console for Notebook" action from the File menu in the notebook, since it probably does not make sense.

**Comment by jtpio** [comment]
Thanks @SylvainCorlay.

RetroLab now supports Code Consoles (added in #197 and released in [v0.3.2](https://github.com/jupyterlab/retrolab/releases/tag/0.3.2)). So I guess this could stay as it provides a nice way to start a console (in a new browser tab) from a notebook and share the kernel state?

https://user-images.githubusercontent.com/591645/134511182-d09697a5-cd14-4b90-acfc-fb59ec963116.mp4

**Comment by jtpio** [comment]
Closing as fixed and answered!

**Comment by SylvainCorlay** [comment]
Ok it seems that i needed to allow it to open other tabs.
