### ISSUE TITLE
The icons for "Open with JupyterLab" and "Open with Classic Notebook" are too similar

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/retrolab#256]
Both use a Jupyter logo, and we need to wait for the tooltip to show in order to know which does what.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/request-for-implementation-a-classic-jupyter-notebook-extension-for-easy-switching-between-lab-retrolab-classic-notebook-nteract/12292/1
