### ISSUE TITLE
JupyterLab extensions that only operate within a notebook do not all work in RetroLab

### ISSUE THREAD

**Issue by gutow** [jupyterlab/retrolab#258]
## Description
I understand that some JupyterLab extensions that access non-notebook areas in JupyterLab are not yet expected to work in RetroLab. However, something is inconsistent about the way RetroLab handles JupyterLab extensions that operate only within a notebook without modifying anything in the other Jupyterlab areas. Extensions/widgets this is known to impact: `plotly`

## Reproduce
1. `pip install plotly numpy pandas` into the environment of JupyterLab/RetroLab.
2. In a new notebook create a simple data set to plot.
```
import pandas as pd
import numpy as np
X = [k*np.pi/10 for k in range(-30,30)]
Y = np.sin(X)
df = pd.DataFrame({'X':X, 'Y':Y})
df['size']=df['X']/3/np.pi
```
3. Plot it.
```
from plotly import graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=df["X"], y=df['Y'],mode='lines+markers',name='sin(x)'))
fig.add_trace(go.Scatter(x=df["X"], y=df['size'],mode='lines',name='y = x')) 
fig.update_layout(template='simple_white')
fig.update_xaxes(mirror='ticks')
fig.update_yaxes(mirror=True)
fig.show()
```
This works in an .ipynb running in JupyterLab but in RetroLab nothing is displayed.

## Expected behavior
Expect the same graph displayed in JupyterLab and RetroLab

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version: FireFox 93.0 or Chromium 95.0.4638.54  
- JupyterLab version: RetroLab 0.3.11

**Comment by jtpio** [comment]
Thanks @gutow for reporting.

I just opened #262 which should fix the issue (if you want to try it on Binder)
