### ISSUE TITLE
CONTRIBUTING.md e2e instructions are out of date

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/retrolab#277]
## Description

`CONTRIBUTING.md` includes information about running end-to-end (e2e) tests as follows:

https://github.com/jupyterlab/retrolab/blob/9010ff543538dd6b15d647dd38ce44626095db84/CONTRIBUTING.md?plain=1#L81-L95

This information is out of date. The `app/test` folder no longer exists in the `retrolab` package. There is a `ui-tests` folder with a `test` subdirectory, but I'm not sure whether this contains the e2e tests to which `CONTRIBUTING.md` currently refers.

## Reproduce

Attempt to follow the instructions in `CONTRIBUTING.md` listed above

## Expected behavior

Nonexistent directory `app/test`

**Comment by jtpio** [comment]
Thanks @jweill-aws for catching this.

There were couple of changes in https://github.com/jupyterlab/retrolab/pull/273. Will update with the new instructions.
