### ISSUE TITLE
Automatically scroll output area with large text outputs

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#287]
### Problem

When printing output that is a large amount of text, there is currently no output scrolling. This means users have to scroll quite far to get to the next code block.

![image](https://user-images.githubusercontent.com/30430/141828938-3aa2c152-7c22-48b6-b392-a41c6fcfb5d7.png)

Compared with classic notebook, which automatically scrolls by default

![image](https://user-images.githubusercontent.com/30430/141828971-9829da3c-2b02-43fb-a166-45ba6f8d6378.png)

(images courtesy @davidwagner from https://github.com/berkeley-dsep-infra/datahub/issues/2992)

### Proposed Solution

In https://github.com/jupyterlab/jupyterlab/issues/4028, a setting was added to JupyteLab to enable this behavior. But it isn't on by default (IIRC). In retrolab, we should turn this on by default!

### Additional context

Am trying to get the large [data8](https://data8.org) class at Berkeley switch from classic notebook to retrolab, and this is part of a series of issues we're trying to tackle before it can be rolled out to total newbie students.

**Comment by yuvipanda** [comment]
@jtpio in https://github.com/berkeley-dsep-infra/datahub/issues/2990#issuecomment-966997264 you suggested running the toggle outputsScrolled command on startup. But that doesn't affect *new* cell creation, does it? Only for cells that already exist?

**Comment by jtpio** [comment]
> But it isn't on by default (IIRC)

Yeah I'm not sure why it's not. Maybe it should be on by default in JupyterLab? Then RetroLab would just inherit the default settings.

> But that doesn't affect new cell creation, does it? Only for cells that already exist?

Looking at the code this indeed seems to only affect the existing cells:

https://github.com/jupyterlab/jupyterlab/blob/a947c0e5cf420b7cf9fe49fe9eb07daeaa81ed5a/packages/notebook/src/actions.tsx#L1378-L1381

Maybe we can listen to new cells being added with the `notebook.model.cells.changed` signal to set the flag automatically.

**Comment by yuvipanda** [comment]
Can we implement this in retrolab first and then upstream? 

I don't understand why a setting wasn't the outcome in https://github.com/jupyterlab/jupyterlab/issues/4028, do you have a sense?

**Comment by jtpio** [comment]
> I don't understand why a setting wasn't the outcome in [jupyterlab/jupyterlab#4028](https://github.com/jupyterlab/jupyterlab/issues/4028), do you have a sense?

Right I thought that would have already been the case and available via the advanced settings editor.
