### ISSUE TITLE
Story for generic document factory

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/retrolab#290]
### Problem

This was first brought at the [JLab team meeting](https://github.com/jupyterlab/team-compass/issues/128#issuecomment-971829367) by @bollwyvl 

Nick modified ipydrawio to [support retrolab](https://github.com/deathbeds/ipydrawio/pull/72). This resulted in quite some hack to replace the file editor by the custom document from ipydrawio factory.

It will be nice if custom factories can be supported out of the box.

### Proposed Solution

As retrolab is single document oriented set through URL, one idea could be to support generic URL pattern `<baseURL>/retro/<factory name>/?path=<path>`. This will support:
- multiple factories for the same path
- unique URL (that can be shared, saved,...)

The challenge is likely to be on the list of core plugins that need to be loaded on that page - we may need to support customization of the base modules in `app/index.js`, to change how core packages are distributed and to support dynamic plugin load.

**Comment by jtpio** [comment]
Thanks @fcollonval for opening this.

> one idea could be to support generic URL pattern

Or maybe via a query string parameter such as `?factory=`, so it also works with JupyterLite.

Probaby the doc manager plugin defined here could be slightly tweaked to open widgets with a different factory:

https://github.com/jupyterlab/retrolab/blob/3b9b2bb17c6a87946bb3100a9210bb43eb32b2ce/packages/docmanager-extension/src/index.ts#L17-L48

**Comment by bollwyvl** [comment]
Yeah... I don't know how much I care about pretty urls, but definitely do
care about getting "free" lite support. And rise would be similar, I
suppose.

On video chat, I went down a similarly aggressive path, but with tree...
That one _would_ make sense as a new url, as it has a server component.
Settings is maybe like that.

Of course we might be able to solve fancy retro urls at lite build time, if
they can be predictably derived from package.json metadata...

**Comment by fcollonval** [comment]
> query string parameter such as `?factory=`, so it also works with JupyterLite

:+1: to get Lite happier :smile:

**Comment by jtpio** [comment]
Thinking about this more, we'll probably want to make it generic enough so it can open other arbitrary widgets in new browser tabs. For example the new settings editor.

**Comment by jtpio** [comment]
Just opened https://github.com/jupyter/notebook/pull/6315 to start exploring this.
