### ISSUE TITLE
Open notebook with editor or JSON doesn't work

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/retrolab#297]
## Description

In the file browser, right-clicking on a Jupyter notebook and selecting "Open With -> Editor" or "Open With -> JSON" opens the notebook, as if "Open With -> Notebook" was chosen.

## Reproduce

1. Right click on a notebook file.
2. Choose "Open With -> Editor" or "Open With -> JSON".
3. See that a notebook document is opened (and a kernel launched), not the file editor or the JSON representation.

## Expected behavior

The file editor or JSON representation should be opened.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Firefox 94.0
- RetroLab version: 0.3.13

**Comment by bollwyvl** [comment]
See also #290

**Comment by parmentelat** [comment]
trying to open jupytext-encoded notebooks, I am experiencing something that may be related

https://github.com/mwouts/jupytext/issues/929

**Comment by jtpio** [comment]
Thanks all. Closing in favor of https://github.com/jupyterlab/retrolab/issues/290 so we can keep the conversation in one place.

**Comment by jtpio** [comment]
This should now be possible with `notebook>=7.0.0a2` (implemented in https://github.com/jupyter/notebook/pull/6315):

![image](https://user-images.githubusercontent.com/591645/159340954-38ceeae0-9158-45ae-bbd8-24d15ebda488.png)
