### ISSUE TITLE
Exiting terminal doesn't close window tab

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/retrolab#299]
### Problem

When exiting a terminal by entering `exit`, it would be nice for the window tab to close as well.
Currently, the user is left with an empty page:

![image](https://user-images.githubusercontent.com/4711805/144869953-8deb1733-54a3-4ff3-8703-bf337707067b.png)

### Proposed Solution

Maybe use:
```javascript
window.close();
```

### Additional context

That would match JupyterLab's behavior (for which the tab is closed).

**Comment by jtpio** [comment]
Thanks @davidbrochart.



> Maybe use:
> 
> ```js
> window.close();
> ```

Right there could be small plugin in the `terminal-extension` package that listens to `widget.disposed` and performs this action.

For reference the classic notebook keeps the terminal widget displayed, and appends `[CLOSED]`:

https://user-images.githubusercontent.com/591645/144883622-9b2f9434-e909-4e09-80aa-9601242790b1.mp4

**Comment by jtpio** [comment]
Thinking about this more, I'm wondering if automatically closing the tab might be a bit too aggressive.

For example we could imagine someone running something in the terminal, and expecting to keep the output of a command displayed on the screen. Ideally we would find a way to replicate the behavior of the classic notebook and keep the terminal widget displayed on the page after `exit`. Although it's true that in JupyterLab the terminal widget is just disposed.

**Comment by davidbrochart** [comment]
Yes, I agree that we should try and keep as close as possible to the classic notebook.
