### ISSUE TITLE
Double slash in console URL

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/retrolab#300]
## Description

Not sure this is a bug, but it looks like the console URL now has a double slash, e.g.:
```
http://localhost:8888/retro/consoles//console-1-33a9d4ee-3873-4611-9edd-c1ff7afee29e
```

## Reproduce

1. Click "New Console"
2. See the URL in the opened window.

## Expected behavior

I wouldn't expect to see a double slash.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Firefox 94.0
- RetroLab version: 0.3.13

**Comment by jtpio** [comment]
Thanks @davidbrochart.

I think the extra slash comes from the path a new console gets when created. For example in JupyterLab it shows up like this:

![image](https://user-images.githubusercontent.com/591645/145004263-36b1c0ae-abd8-4320-b04f-69cc9a0b18e3.png)

However there is no extra slash when creating a "New Console for Notebook":

![image](https://user-images.githubusercontent.com/591645/145004506-8182087c-e8c4-4580-a369-f7e62bf52d09.png)

**Comment by davidbrochart** [comment]
> I think the extra slash comes from the path a new console gets when created.

Maybe the slash in the console path is not needed then (in JupyterLab)?

**Comment by jtpio** [comment]
Looks like the slash is coming from this place in the code: 

https://github.com/jupyterlab/jupyterlab/blob/a353063ba61cf6298e853ab3ad841f73da07032e/packages/console/src/panel.ts#L58

**Comment by davidbrochart** [comment]
Thanks @jtpio, I opened https://github.com/jupyterlab/jupyterlab/pull/11626.

**Comment by jtpio** [comment]
This should be fixed next time we update the `@jupyterlab/*` packages to `3.2.6+`.
