### ISSUE TITLE
Classic notebook and retrolab cannot be used by the lab started by jupyter labhub

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/retrolab#311]
Classic notebook and retrolab cannot be used by the lab started by jupyter labhub

![image](https://user-images.githubusercontent.com/39434627/147525272-3d396d8c-b0fa-496e-808d-7a473a15d9f6.png)

When accessing these two buttons, the status is 404

**Comment by jtpio** [comment]
Thanks @icankeep for reporting.

Normally both classic and retrolab should work with `jupyterhub`. And these two buttons should handle the base URL:

https://github.com/jupyterlab/retrolab/blob/45bc2c5845e8b13f5124bbc9292097673649680f/packages/lab-extension/src/index.ts#L130

Would you mind sharing the URLs users are redirected to?

**Comment by icankeep** [comment]
https://mydomain.com/user/my_user_name/retro/tree/output.ipynb

**Comment by icankeep** [comment]
retro: `https://mydomain.com/user/my_user_name/retro/tree/output.ipynb`

classic notebook: `https://mydomain.com/user/my_user_name/tree/output.ipynb`

**Comment by jtpio** [comment]
The URLs look good.

How are the `jupyterlab`, `notebook` and `retrolab` packages installed?

**Comment by jtpio** [comment]
@icankeep were you able to make progress with this?

Closing as the RetroLab / Notebook v7 is ongoing work to make it possible to install the different interfaces in a single setup: https://github.com/jupyter/notebook-team-compass/issues/5#issuecomment-1085254000.
