### ISSUE TITLE
Update npm packages to the `@jupyter-notebook` scope

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/retrolab#313]
### Problem

At the moment we are publishing the npm packages under the `@retrolab` scope.

Now that the [Notebook v7 JEP](https://github.com/jupyter/enhancement-proposals/pull/79) has been merged and in preparation for the first `7.0.0a0` pre-release, we should consider renaming the `npm` packages to use the `@jupyter-notebook` scope.

### Proposed Solution

This should only consist in a search / replace, and make sure the `publishConfig` is set to `public`. The releaser will take of the publishing. 

### Additional context

Other organizations on npm such as `@notebook` and `@jupyter` seem to be taken. But we manage to get a hold on `@jupyter-notebook` which can be used for this project but also for other projects related to the Jupyter notebook ecosystem.

**Comment by afshin** [comment]
I just took a look and [npm/jupyter](https://www.npmjs.com/package/jupyter ) was published by @rgbkrk 🤓

**Comment by jtpio** [comment]
Nice. Although this corresponds to a single package?

@rgbkrk do you happen to also own the `@jupyter` organization on `npm`?

**Comment by afshin** [comment]
I can't remember for sure but I think NPM allows changing a package name to an org name. But that might not be the case.

**Comment by rgbkrk** [comment]
I'll double check now.

**Comment by rgbkrk** [comment]
I do not own nor am I a member of the `@jupyter` org on npm.

**Comment by bollwyvl** [comment]
As discussed in the notebook meeting: I think somebody found it's possible to turn a _user_ into an org, but not a _package_. 

So the un- `@`-prefixed at e.g. https://www.npmjs.com/package/jupyter doesn't really push things forward much.

**Comment by afshin** [comment]
> So the un- `@`-prefixed at e.g. https://www.npmjs.com/package/jupyter doesn't really push things forward much.

At least it means no one can squat the `@` but I wonder if we can ask NPM support about this.

**Comment by rgbkrk** [comment]
Someone has the `@jupyter` scope. I tried to register it yesterday and couldn't. IIRC @minrk or @Carreau grabbed `@jupyter` a long time ago.

**Comment by Carreau** [comment]
I don't think that's me.
