### ISSUE TITLE
Can't open notebook file in editor or in JSON View

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#317]
## Description

Right clicking a notebook in tree view shows options to 'open with' a JSON View or a text editor. However, clicking either of these opens up a new tab in notebook view.

## Reproduce

1. Install latest retrolab (0.3.15)
2. Open a directory containing notebooks
3. Right click a notebook, and select 'Open With', then 'Editor' or 'JSON View'
4. A new tab opens with the notebook in notebook view, rather than the view that was chosen

## Expected behavior

Either a new tab should open up with the correct view, or the context menu options should be removed.

**Comment by jtpio** [comment]
Thanks @yuvipanda.

This looks a like a duplicate of https://github.com/jupyterlab/retrolab/issues/297? (and related to https://github.com/jupyterlab/retrolab/issues/290)

**Comment by yuvipanda** [comment]
Ah, i clearly had not searched well enough! Closing as duplicate of https://github.com/jupyterlab/retrolab/issues/297
