### ISSUE TITLE
Save and export notebook as menu item not expanding

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#331]
## Description

File -> Save and export as doesn't seem to work. Clicking it shows a tiny scrollbar but doesn't pop out the child menu.

![image](https://user-images.githubusercontent.com/30430/151224180-427c7ae2-03b2-489e-afcf-0d01968445b8.png)

Works fine on JupyterLab in the same environment

<img width="598" alt="image" src="https://user-images.githubusercontent.com/30430/151224227-fd750d88-c117-4cc2-8866-9e5b063cdd72.png">

## Reproduce

1. Open current retrolab in binder: https://mybinder.org/v2/gist/jtpio/4a6a34da66b32249e28df718ec30e4d7/master?urlpath=/retro/notebooks/tour.ipynb
2. Open file menu
3. Try to expand 'Save and export notebook as...'
4. No menu appears on the right.

**Comment by yuvipanda** [comment]
There's nothing in the serverlogs for this either.

**Comment by yuvipanda** [comment]
Nor anything helpful in the browser console

**Comment by jtpio** [comment]
Thanks @yuvipanda for reporting.

It might be related to https://github.com/jupyterlab/jupyterlab/pull/10094 which moved the functionality to another plugin, that RetroLab would now need to include.

**Comment by jtpio** [comment]
Should be fixed by https://github.com/jupyterlab/retrolab/pull/337
