### ISSUE TITLE
Ability to customize retrolab interface

### ISSUE THREAD

**Issue by holzschu** [jupyterlab/retrolab#350]
### Problem

I'm running retrolab on a computer where the user cannot run terminals (it's an iPad). To avoid user confusion, I would like the ability to remove the "New Terminal" button (and "New Console", too). In Jupyterlab, setting `terminals_enabled` to `False` will remove the "New Terminal" button in the Launcher tab. I haven't found a similar feature in retrolab (I think it's because the buttons are generated directly in Javascript, which makes a very compact system, at the expanse of customization).

### Proposed Solution

I would like to suggest introducing a way to disable individual buttons in the interface. Possibly through a variable, that the user could set in a configuration file?

### Additional context

Current user interface: 
![image](https://user-images.githubusercontent.com/8070736/153727245-5927cfb6-2842-410a-bf07-f2c3d9d61802.png)

Desired user interface (after customization): 
![image](https://user-images.githubusercontent.com/8070736/153727462-e8f7262b-0cf2-4e10-baaa-6c5b81ad1bc0.png)

**Comment by holzschu** [comment]
Well I'll be damned! It works! I'm in awe.
For a more permanent solution, I ended up creating the config file `Library/etc/jupyter/labconfig/page_config.json`, which contains: 
```
{
  "disabledExtensions": {
    "@retrolab/tree-extension:new-console": true,
    "@retrolab/tree-extension:new-terminal": true
  }
}
```
(which is the same, but stored as settings). Thank you so much!

While we're on the topic of customization, is there a way to add extra buttons to the top toolbar for a notebook? I would need two extra buttons to account for the specificities of iOS. 

![image](https://user-images.githubusercontent.com/8070736/153762390-2478cac6-b77e-4338-8912-b2a6b36a029d.png)

**Comment by jtpio** [comment]
> which is the same, but stored as settings

Yes that also works.

> While we're on the topic of customization, is there a way to add extra buttons to the top toolbar for a notebook? I would need two extra buttons to account for the specificities of iOS.

Yes this is possible via an extension: https://jupyterlab.readthedocs.io/en/latest/extension/notebook.html#adding-a-button-to-the-toolbar. There is an example in the extension examples repo: https://github.com/jupyterlab/extension-examples/tree/master/toolbar-button

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/notebook/pull/6336

In the next Notebook v7 pre-release it will be possible to more easily customize the file browser toolbar items via the settings system, just like in JupyterLab.

@holzschu feel free to open new issues in the notebook directly if you think this needs to be iterated on more. Thanks!
