### ISSUE TITLE
autocomplete not working with development repository

### ISSUE THREAD

**Issue by holzschu** [jupyterlab/retrolab#359]
## Description

When I try to run autocomplete with the development repository, nothing happens. In the JavaScript console,  `jupyterapp.commands._commands` shows that the `completer:invoke-*` commands are not available. It seems the completer extension was not loaded.

## Reproduce

- launch retrolab in binder with the development repository
- create a cell
- type "imp", then tab
- a white tab is inserted in the cell.

Launching retrolab with the current release gives the expected result, the autocomplete menu appears.

## Expected behavior

I expected the autocomplete menu to appear.

## Context

- Operating System and version: OSX 12.3 and iPadOS 15.4
- Browser and version: Safari 15.4
- JupyterLab version: 4.0.0a22
- Retrolab version: 0.4.0a1

<details><summary>Troubleshoot Output</summary>
<pre>
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @holzschu for reporting.

This was noticed in https://github.com/jupyter/notebook/pull/6314 when updating to the latest JupyterLab 4.0 packages.

Some plugins have changed upstream in JupyterLab and can be seen in the diff of https://github.com/jupyter/notebook/pull/6314. For example `@jupyterlab/completer-extension:notebooks` -> `@jupyterlab/notebook-extension:completer`.

Probably this is not an issue on the `0.3.x` branch in the retrolab repo which still uses the JupyterLab 3.3.x packages.

**Comment by jtpio** [comment]
@holzschu let's close this since this should now be fixed on the `main` branch in the notebook repo: https://github.com/jupyter/notebook/

Also development is now happening in https://github.com/jupyter/notebook (https://github.com/jupyterlab/retrolab/issues/356)
