### ISSUE TITLE
Install service is down

### ISSUE THREAD

**Issue by stishka1** [jupyterlab/retrolab#365]
Hello
Install service is down
Whats happening?
Why I cant install python libraries???
https://pastenow.ru/f5186551868b26b943081cf28cdf6b6b

**Comment by jtpio** [comment]
Closing as RetroLab is now being developed as Notebook 7 in https://github.com/jupyter/notebook.

Feel free to open a new issue in https://github.com/jupyter/notebook if you would like to discuss this more, thanks!
