### ISSUE TITLE
Support for code consoles

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/retrolab#49]
It should be possible to reuse the existing `console-extension` from JupyterLab.

Then consoles could be available via the `/classic/consoles/1` endpoint like terminals.

The main question is whether we want to add them to JupyterLab Classic (with the trade-off of making the interface too complicated).

Code consoles in JupyterLab:

![image](https://user-images.githubusercontent.com/591645/102134293-9aca7080-3e56-11eb-9748-3c5c6065b92c.png)

**Comment by choldgraf** [comment]
This would be super useful for me - I always find myself awkwardly running one-off `!` commands within cells. It would be great if we could use a keyboard shortcut to pop up a quick terminal to run (e.g., I believe vscode uses `` ctrl+` `` for a lightweight terminal)

**Comment by jtpio** [comment]
Do you think it would be better to have code consoles open in a new browser tab, just like everything else in JupyterLab Classic?

Or were you thinking of some kind of popup / dialog with a cell, to be able to execute something in the same kernel as the notebook, but without modifying the notebook itself?
If so then it could indeed be a more generic lab extension, which would also work out of the box in JupyterLab Classic.

**Comment by choldgraf** [comment]
I was imagining the latter. Basically a window that hovers over everything else and gives access to a shell (or maybe a kernel window as an option as well), and pressing the shortcut again causes the console window to disappear

**Comment by jtpio** [comment]
Then having something like this in core lab could be the way to go. And JupyterLab Classic would inherit it.

Maybe this dialog could even be used for evaluating code when using the debugger (https://github.com/jupyterlab/jupyterlab/issues/9111), if all it does is sending code to the kernel for execution.

**Comment by choldgraf** [comment]
Yeah, i think that for certain kinds of terminal interactions, it is more convenient to have a window that quickly pops up and then goes away, rather than going through the launcher tab -> launch terminal tab workflow

**Comment by jtpio** [comment]
Sounds like this could probably be experimented with in a third-party extension first.

Otherwise, would you like to open an issue in https://github.com/jupyterlab/jupyterlab, so it's more visible and maybe someone would like to give it a shot?

**Comment by choldgraf** [comment]
I actually did but it didn't get much response 👍 

https://github.com/jupyterlab/jupyterlab/issues/8801

**Comment by jtpio** [comment]
Thinking about it a bit more, a console in its own browser tab would be quite useful (also discussed in https://github.com/jtpio/jupyterlite/issues/148).  

Marking as good first issue if someone would like to take a look (even partially). Happy to help and provide guidance on the implementation, so don't hesitate to comment here if someone wants to pick it up!

The implementation might similar to the PR that added support for terminals (https://github.com/jupyterlab/retrolab/pull/23), but instead using the `@jupyterlab/console` and `@jupyterlab/code-console` packages.
