### ISSUE TITLE
Long term plans for this repo?

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/retrolab#81]
Just wondering what your long term plans are for this project. Do you hope to get this into the jupyterlab org ? Or keep it a personal project?

**Comment by jtpio** [comment]
Yes I think the plan will be to move the repo to the `jupyterlab` organization on GitHub and make it an official Jupyter sub-project (it was briefly discussed at one of the JupyterLab meetings). Probably in the coming weeks.

I really like the idea of having several distributions for JupyterLab (just like for JupyterHub with TLJH and ZTJH), with JupyterLab Classic being one of these distributions.

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/team-compass/issues/119

**Comment by jtpio** [comment]
Closing since the repo has now been moved to the `jupyterlab` organization.

xref this comment for more details and context: https://github.com/jupyterlab/team-compass/issues/119#issue-798400525
