### ISSUE TITLE
404 behind a reverse proxy

### ISSUE THREAD

**Issue by DuckieNukeEm** [jupyterlab/retrolab#92]
My jupyter lab sits behind a reverse proxy, I added this exstension, showed up fine. When I click to have jupyter lab pop over to jupyter classic, I get a 404 error. What should I add to nginx help resolve this?

**Comment by jtpio** [comment]
@DuckieNukeEm could it be because the JupyterLab classic urls such as `/classic/notebooks` and `/classic/tree` are not allowed?

**Comment by DuckieNukeEm** [comment]
That was my thought, and have modified the rules to allow it:

```
 location ~* /jupyter/(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket|classic)/ {
STUFF 
}
```
As my 8th grade math teacher would say, No go joe (IE, didn't work)

Would I need to modify ...|classic to  ...|classic/notebooks|/classic/tree?

**Comment by jtpio** [comment]
Closing as RetroLab is now being developed as Notebook 7 in https://github.com/jupyter/notebook.

Feel free to open a new issue in https://github.com/jupyter/notebook if you would like to discuss this more, thanks!
